### ISSUE TITLE
제대로 된 Port 정보가 출력되지 않는 버그

### ISSUE THREAD

**Issue by snoopspy** [truculentas/pcap-test#1]
참고하시기 바랍니다.

https://github.com/truculentas/pcap-test/assets/4080232/68e671e4-f59c-4b94-a64b-cc2d469cc64d

**Comment by truculentas** [comment]
https://github.com/truculentas/pcap-test/blame/main/parser.c#L43

오류 원인: ip header의 'total length'가 아닌 'header length'을 이용해 indexing을 수행했어야 함.

**Comment by truculentas** [comment]
github issue 확인 및 수정하였고 close하였습니다.

주말에 귀중한 시간 내어 확인해주시고, 피드백으로 영상까지 만들어 올려주신 점 정말 감사드립니다. 영상 확인하여 쉽게 고칠 수
있었습니다.

김민재 올림

2023년 7월 8일 (토) 오후 3:51, Gilbert Lee ***@***.***>님이 작성:
